---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - "recipe[odi-quirkafleeg-backend::default]"
      - "recipe[mongodb::mongodb_org_repo]"
      - "recipe[odi-mongodb]"      
    attributes:
